export const metadata = {
  title: "Urban Canvas",
  description:
    "Urban Canvas is a social media platform where street art is socially mapped. Focused solely on murals curated by local artists, users can upload and share artwork from around the world. Celebrate and explore the most inspiring murals in one place.",
 keywords: [
  "street art",
  "murals",
  "urban canvas",
  "local artists",
  "art sharing platform",
  "public art",
  "social media for artists",
  "mural map",
  "graffiti art",
  "street murals",
  "orlando murals",
  "orlando street art",
  "orlando art",
  "orlando artists",
  "orlando muralists",
  "miami murals",
  "miami street art",
  "new york street art",
  "los angeles murals",
  "chicago street art",
  "tampa street art",
  "atlanta murals",
  "san francisco street art",
  "seattle murals",
  "boston street art",
  "washington dc murals",
  "global murals",
  "art mapping",
  "art discovery platform",
  "art curation",
  "street art community",
  "mural enthusiasts",
  "art lovers",
  "urban exploration",
  "cultural murals",
  "street art culture",
  "artistic mapping",
  "urban art platform",
  "art community",
  "global street art",
  "art discovery",
  "cultural expression",
  "art enthusiasts",
  "urban culture",
  "mural photography",
  "local culture",
  "artistic inspiration",
  "street art photography",
  "artistic collaboration"
],
  openGraph: {
    title: "Urban Canvas",
    description:
      "A global social media platform for street art lovers. Discover, share, and map murals from local artists around the world.",
    url: "https://urbancanvas.vercel.app/",
    siteName: "Urban Canvas",
    images: [
      {
        url: "/urbanmural.png", 
        width: 1200,
        height: 630,
        alt: "Urban Canvas mural preview",
      },
// 
    ],
    locale: "en_US",
    type: "website",
    twitter: {
  card: "summary_large_image",
  title: "Urban Canvas",
  description: "A global social media platform for street art lovers. Discover, share, and map murals from local artists around the world.",
  images: ["https://urbancanvas.vercel.app/urbanmural.png"],
}
  },
};